// /// Styles - Template for what [map|struct of options] of styles would look like
// // ---------------------------------------------------------------

// /// Map gives flexibility for any style, struct of options would be [higher performance?] but more rigid...
// /// May allow maps to be used in `.ui` file that get merged together to form the struct...
